apiVersion: 1
deleteDatasources:
  - name: qsphere
    orgId: 1

datasources:
  - name: qsphere
    type: postgres
    access: proxy
    orgId: 1
    url: ${PG_HOST}:${PG_PORT}
    user: ${PG_USER}
    database: ${PG_NAME}
    jsonData:
      postgresVersion: 1000
      sslmode: disable
    secureJsonData:
      password: ${PG_PASS}
    version: 1
    editable: true