{
 "title": "QSphere Sprint",
 "tags": [ "QSphere" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PROJECT_UUID",
    "query": "SELECT project.uuid FROM project WHERE project.status != 'delete' ORDER BY 1"
   },
   {
    "name": "PROJECT",
    "query": "SELECT project.name FROM project WHERE project.uuid = '$PROJECT_UUID' ORDER BY 1"
   },
   {
    "name": "SPRINT_UUID",
    "query": "SELECT sprint.uuid FROM sprint INNER JOIN project ON sprint.project = project.uuid WHERE project.uuid = '$PROJECT_UUID' AND sprint.status != 'delete' ORDER BY 1 DESC"
   },
   {
    "name": "SPRINT",
    "query": "SELECT sprint.name FROM sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1"
   },
   {
    "name": "REQUIREMENT",
    "query": "SELECT unnest(value) FROM issue_config INNER JOIN sprint ON sprint.issue_config = issue_config.uuid, jsonb_to_record(requirement) AS x(value text[]) WHERE sprint.uuid = '$SPRINT_UUID' GROUP BY 1"
   },
   {
    "name": "START_DATE",
    "query": "SELECT to_char(capture_time, 'YYYY-MM-DD') FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1 LIMIT 1"
   },
   {
    "name": "END_DATE",
    "query": "SELECT to_char(capture_time, 'YYYY-MM-DD') FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1 DESC LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Sprint [$SPRINT] ( $START_DATE ~ $END_DATE )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "[$SPRINT] Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_capture_sprint_level.capture_time AS \"time\", CAST(issue_capture_sprint_level.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' AND sprint.status != 'delete' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_capture_sprint_level.capture_time AS \"time\", CAST(issue_capture_sprint_level.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' AND sprint.status != 'delete' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_capture_sprint_level.capture_time AS \"time\", CAST(issue_capture_sprint_level.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' AND sprint.status != 'delete' ORDER BY 1"
    }
   ]
  },
  {
   "title": "[$SPRINT] Bug Categories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(issue_capture_sprint_level.capture_time), CAST(issue_capture_sprint_level.category::json->>'newfeature' AS integer) AS \"New Feature\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_capture_sprint_level.capture_time), CAST(issue_capture_sprint_level.category::json->>'previous' AS integer) AS \"Previous\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_capture_sprint_level.capture_time), CAST(issue_capture_sprint_level.category::json->>'regression' AS integer) AS \"Regression\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1"
    },
    {
     "rawSql": "SELECT $__time(issue_capture_sprint_level.capture_time), CAST(issue_capture_sprint_level.category::json->>'others' AS integer) AS \"Others\" FROM issue_capture_sprint_level INNER JOIN sprint ON sprint.uuid = issue_capture_sprint_level.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 1"
    }
   ]
  },
  {
   "title": "[$SPRINT] Bug Found In RC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_capture_static_sprint.capture_time AS \"time\", key, value FROM issue_capture_static_sprint INNER JOIN sprint ON sprint.uuid = issue_capture_static_sprint.sprint, jsonb_each(in_rc) WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 2"
    }
   ]
  },
  {
   "title": "[$SPRINT] Bug Found Since",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_capture_static_sprint.capture_time AS \"time\", improve AS \"Regression Improve\", newfeature AS \"New Feature\", qamissed AS \"QA Missed\", others AS \"Others\" FROM issue_capture_static_sprint INNER JOIN sprint ON sprint.uuid = issue_capture_static_sprint.sprint , jsonb_to_record(found_since) AS x(improve int, newfeature int, qamissed int, others int) WHERE sprint.uuid = '$SPRINT_UUID' ORDER BY 1"
    }
   ]
  },
  {
   "title": "[$SPRINT] New Feature Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_req_latest.capture_time AS \"time\", issue_req_latest.name, CAST(issue_req_latest.status::json->>'total' AS integer) FROM issue_req_latest INNER JOIN sprint ON sprint.uuid = issue_req_latest.sprint INNER JOIN project ON project.uuid = sprint.project WHERE project.name = '$PROJECT' AND sprint.name = '$SPRINT' ORDER BY 3 DESC"
    }
   ]
  },
  { "title": "Requirement [$REQUIREMENT]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "[$REQUIREMENT] Bug Verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'verified' AS integer) AS \"Verified\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'fixed' AS integer) AS \"To Be Verified\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    },
    {
     "rawSql": "SELECT issue_req.capture_time AS \"time\", CAST(issue_req.status::json->>'fixing' AS integer) AS \"To Be Fixed\" FROM issue_req INNER JOIN sprint ON sprint.uuid = issue_req.sprint INNER JOIN project ON project.uuid = sprint.project WHERE issue_req.name = '$REQUIREMENT' AND sprint.name = '$SPRINT' AND project.name = '$PROJECT' ORDER BY 1"
    }
   ]
  }
 ]
}